### ISSUE TITLE
run-druid assumes "current" directory fo the cp

### ISSUE THREAD

**Issue by cywjackson** [implydata/distribution#11] opened 2016-07-07 02:30 UTC
in a production installation, we want to separate out our "data dir" and "install dir" (also "config dir"). However, the "run-druid" assumes the classpath to pick up current directory to pick up `"dist/druid/lib/*"`

Out of the box it works, but once I change my current directory, this fails.

Even if that's not the case, assuming "working directory" and append classpath is just bad anyway. Attaching a suggested soln to use `$WHEREAMI/../` to at least set it to with fully qualified path

[run-druid.diff.txt](https://github.com/implydata/distribution/files/351267/run-druid.diff.txt)

**Comment by gianm** [comment] 2016-07-07 03:01
I guess this doesn't normally come up because the `run-druid` script was intended to be run under `supervise` (http://imply.io/docs/latest/operations#service-supervision-and-logging), which chdirs to the root of the distribution before running any of the commands, no matter where it was invoked from. But this is still a good suggestion for people that don't want to use `supervise` for some reason.

Thanks for the patch @cywjackson. Closing the issue, this will be included in the next release.

**Closed by gianm** 2016-07-07 03:01 UTC
